name: fablab-service

services:
  fablab-web:
    build:
      context: .
      args:
        VITE_BASE: ${VITE_BASE}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: fablab-web
    restart: unless-stopped
    ports:
      - 9092:80
    networks:
      - fablab-service-network
networks:
    fablab-service-network:
        name: fablab-service-network
        driver: bridge
