name: fablab-service

services:
  fablab-web:
    build: .
    container_name: fablab-web
    restart: unless-stopped
    ports:
      - 9092:80
    env_file:
      - ./.env
    networks:
      - fablab-service-network
